[workspace]
members = ["core", "gamegirl", "tests"]
resolver = "2"

[profile.release]
debug = true

[profile.prod]
inherits = "release"
strip = true
codegen-units = 4
lto = true

[profile.dev]
opt-level = 1
