[workspace]
members = ["core", "gamegirl", "tests", "tests/tracing"]
resolver = "2"

[profile.release]
debug = true
incremental = true

[profile.prod]
inherits = "release"
strip = true
codegen-units = 4
lto = true
incremental = false

[profile.dev]
opt-level = 1
