[package]
name = "gamegirl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.5"

[dependencies.eframe]
git = "https://github.com/mccolljr/egui.git"
branch = "mccolljr/texture_filter"

[workspace]
members = [".", "tests"]

[profile.release]
lto = true
strip = true
