[package]
name = "gamegirl"
default-run = "gamegirl_bin"
version = "0.1.0"
authors = ["Ellie Leela Ang. <git@angm.xyz>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "gamegirl_bin"
path = "src/main.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cpal = "0.13.5"
gilrs = "0.9.0"
rfd = "0.8.2"
futures-executor = "0.3.21"
serde = "1.0.137"
serde_arrays = "0.1.0"
bitflags = "1.3.2"
bincode = "1.3.3"
zstd = { version = "0.11.2", default-features = false }

[dependencies.eframe]
git = "https://github.com/mccolljr/egui.git"
branch = "mccolljr/texture_filter"
features = ["persistence"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
tracing-wasm = "0.2.1"
wasm-bindgen-futures = "0.4.30"
web-sys = { version = "0.3.57", features = ["Storage", "Window"] }
base64 = "0.13.0"
cpal = { version = "0.13.5", features = ["wasm-bindgen"] }
zstd = { version = "0.11.2", default-features = false, features = ["wasm"] }


[workspace]
members = [".", "tests"]

[profile.release]
lto = true
strip = true
