[package]
name = "gamegirl"
default-run = "gamegirl_bin"
version = "0.1.0"
authors = ["Ellie Leela Ang. <git@angm.xyz>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "gamegirl_bin"
path = "src/main.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cpal = "0.13.5"

[dependencies.eframe]
git = "https://github.com/mccolljr/egui.git"
branch = "mccolljr/texture_filter"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
tracing-wasm = "0.2"
cpal = { version = "0.13.5", features = ["wasm-bindgen"] }


[workspace]
members = [".", "tests"]

[profile.release]
lto = true
strip = true
